### ISSUE TITLE
[Nomination] : Add Fazeel Usmani to Rookie list

### ISSUE THREAD

**Issue by FazeelUsmani** [Polkadot-Heroes/Members#34]
### Technical expertise

I know Rust, Polkadot Substrate, IPFS, Python, Java, Javascript, React, Kubernetes, GCP and much more. 
https://github.com/FazeelUsmani/Dropbox-Clone-using-Substrate-v1,
https://github.com/FazeelUsmani/Substrate-Kitties,
https://github.com/FazeelUsmani/rust-by-practice,
https://github.com/FazeelUsmani/Hyperledger-Fabric-2.x,
https://github.com/FazeelUsmani/dotsamaworld,
https://github.com/FazeelUsmani/spheron,
https://github.com/FazeelUsmani/Polkadot,
https://github.com/FazeelUsmani/quadratic-voting-parachain,

### Community involvement

I've not been actively involved in the community but I loved to contribute. Can you share any references to contribute?

### Content creation

https://github.com/FazeelUsmani/Amazon-SDE-Preparation - This repository involved all the problems which I solved during my interview preparation helping around 1,000 computer enthusiasts. These problems involves documentation which speaks about how to develop an intuition when you see a problem, find a solution and look for different ways to optimize it. 

https://github.com/FazeelUsmani/Scaler-Academy - Even this repository is stargazed by many people and some of them ask me in an email regarding how you've done all these problems or when they're stuck at somewhere and usually ask for guidance. 
Here are some excerpts of our chats:

<img width="1332" alt="image" src="https://github.com/Polkadot-Heroes/Members/assets/8823157/d2afd0ba-4482-45fc-bdf1-385528e3de28">
<img width="1332" alt="image" src="https://github.com/Polkadot-Heroes/Members/assets/8823157/88990fa3-5065-4d09-8cd2-4fc57af7f246">
<img width="1332" alt="image" src="https://github.com/Polkadot-Heroes/Members/assets/8823157/3bb8477b-3889-4441-ae29-01e07c19c6af">
<img width="1332" alt="image" src="https://github.com/Polkadot-Heroes/Members/assets/8823157/8ae6d46f-551e-45f2-8711-6cef96c4466a">
<img width="1351" alt="image" src="https://github.com/Polkadot-Heroes/Members/assets/8823157/ea652d66-27e1-43c5-a636-fb7f97405c48">
<img width="1262" alt="image" src="https://github.com/Polkadot-Heroes/Members/assets/8823157/54fc26b0-f82e-4d8c-9593-f9b1378868a2">

### Leadership experience

I'm a pro at hosting meetups. Google Maps team named me a **meetup master**. Here is my local guides profile, you can check my meetup posts
https://www.localguidesconnect.com/t5/General-Discussion/Fazeel-Usmani-loves-to-host-meetups-at-various-parts-of-the/td-p/1652667

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Nagarjuna-Sagar-Dam-Photo-Walk/td-p/1651799

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Mumbai-Food-Crawl/td-p/1626602
`
 https://www.localguidesconnect.com/t5/user/viewprofilepage/user-id/34190

https://www.localguidesconnect.com/t5/General-Discussion/The-most-interesting-thing-I-ve-done-as-a-Local-Guide-Hosting/td-p/2355323

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Clean-The-World-Hyderabad/td-p/2309515

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Republic-Day-Celebration-2020/td-p/2176277

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Istanbul-Food-Crawl/td-p/2123760

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Bogatha-Waterfall-Photo-Walk/td-p/2090006

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Indi-Grill-Food-Crawl/td-p/2195481

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Republic-Day-Celebration-2020/td-p/2176277

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Bogatha-Waterfall-Photo-Walk/td-p/2090006

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Aurangabad-Photo-Walk/td-p/2026113

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Bangalore-Geo-Walk/td-p/1896786

https://www.localguidesconnect.com/t5/General-Discussion/Recap-Sudha-Car-Museum-Photo-Walk/td-p/1590133

### Mentorship experience

Yes

### Mentorship details

I've been mentoring at Scaler Academy which teaches Data Structures & Algorithms, Low level design, High level design of systems, databases, networks, operating systems and core computer concepts to become a skilled software engineer.

**Comment by cenwadike** [comment]
It appears you may want to change the title of the issue to something like so "Nomination] : Fazeel Usmani"

**Comment by hummusonrails** [comment]
Hi @FazeelUsmani,

Did you intend to open a self-nomination request for Hero status or are you attempting to add yourself to the list of Rookies?

According tot he title, it appears you are doing the latter, which is great, as you have not done that yet.

Can you please follow these instructions: [https://github.com/Polkadot-Heroes/Members/tree/main/Rookies#contributing](https://github.com/Polkadot-Heroes/Members/tree/main/Rookies#contributing).

After you have added yourself to the Rookies list, and you feel you are ready to self-nominate for Hero status, please come back to this and re-open this Issue revising the title to `[Nomination]: Fazeel Usmani`.

You can read the criteria for review for Hero status also in this repository at [https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md](https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md).

Ben
