### ISSUE TITLE
[Nomination] : Immanuel John

### ISSUE THREAD

**Issue by Immanuel-john** [Polkadot-Heroes/Members#40]
### Technical expertise

Certainly, I have been actively involved in projects within the Polkadot/substrate ecosystem for the past two years. One notable project I've worked on is an independent chain where I built a decentralized exchange (DEX) utilizing the Substrate framework. You can explore the results of this work at [VTB DEX](https://vtbdex.com/explorer). In this role, I served as a primary Substrate developer, responsible for designing custom pallets tailored to specific requirements, crafting robust unit tests, conducting benchmarking, and contributing to the deployment of the network.

Currently, I am serving as a Rust/Substrate engineer at Ternoa, a project centered around NFTs within the Polkadot ecosystem. Ternoa has ambitions of becoming a parachain in the near future. Our codebase is open source and available on GitHub at [Ternoa Node](https://github.com/capsule-corp-ternoa/ternoa-node), [Ternoa Pallets](https://github.com/capsule-corp-ternoa/ternoa-pallets) My role involves working on various aspects of the project, ranging from protocol development to ensuring the reliability and scalability of the infrastructure.

Throughout these experiences, I have honed my skills in Rust programming, Substrate development, and blockchain technology, allowing me to contribute effectively to the growth and innovation within the Polkadot/substrate ecosystem.

### Community involvement

Certainly, my involvement in the Polkadot community includes the following:

Meet-ups and Hackathons: I have actively participated in Polkadot-related meet-ups and hackathons in India. These events have provided a platform to connect with fellow developers, enthusiasts, and experts in the field, contributing to my learning and networking within the community.

Substrate StackExchange Participation: I have been an active contributor on the Substrate StackExchange platform. I've both provided solutions to questions raised by others and asked valid questions myself. This exchange of knowledge and engagement with the community has been instrumental in enhancing my understanding of Substrate and its related technologies. You can find my contributions on the [Substrate StackExchange profile](https://substrate.stackexchange.com/users/427/immanuel-john).

These activities have allowed me to actively engage with the Polkadot and Substrate communities, share my insights, learn from others, and contribute to the growth of the ecosystem.

### Content creation

Absolutely, I'm quite active on LinkedIn where I regularly share insightful content related to the Polkadot/substrate ecosystem and the Rust programming language that powers it. I find it essential to keep the community informed and engaged through my posts. Here are a few of my recent posts that delve into various aspects of the ecosystem:

https://tinyurl.com/mt2anv24 ,
https://tinyurl.com/5xsx3mj5 ,
https://tinyurl.com/masjxt7  ,
https://tinyurl.com/3rd8hxjw ,
https://tinyurl.com/2p8v7y8p ,
https://tinyurl.com/4an5khmn 

In addition to these posts, I've also authored several articles that provide in-depth insights into various aspects of Polkadot, Substrate, and Rust programming:

https://tinyurl.com/3d2h9fab , 
https://tinyurl.com/mte4j4ct , 
https://tinyurl.com/ymrw4snx , 
https://tinyurl.com/9k2vuhch , 
https://tinyurl.com/32vnv8kx

Also I have a [Youtube channel](https://www.youtube.com/watch?v=yafoJ0sGJz4&list=PLdIzVVjNvusSYhqEH2_fPFtcVZEAlVs4Q) where I teach about Rust programming in my regional language - 
Furthermore, I believe in collaborative learning and active participation. That's why you'll also find me on Substrate StackExchange, where I contribute solutions, ask meaningful questions, and engage with the community. You can explore my interactions and contributions on the platform here - https://substrate.stackexchange.com/users/427/immanuel-john.

All of these platforms are a reflection of my dedication to sharing knowledge, fostering discussions, and contributing to the continuous growth of the Polkadot/substrate ecosystem.

### Leadership experience

**Technical Workshops and Web2 Leadership:**

I've organized and led technical workshops aimed at educating students and enthusiasts. Although these workshops were live events without recorded sessions, you can get a glimpse of them through the following clips: [Workshop Clip 1](https://www.instagram.com/reel/Cjw9YcZBVxG/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==), [Workshop Clip 2](https://www.instagram.com/reel/Ci7kqRcs2wU/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==), [Workshop Clip 3](https://www.instagram.com/p/Cjclo-jBrNq/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==).

**Educating College Students about Web3 and Blockchain:**

I've had the privilege of educating hundreds of college students about the concepts of Web3 and blockchain. This initiative aimed to bridge the gap between traditional education and the cutting-edge technologies of the decentralized world. The impact of these sessions can be seen in the [video](https://www.linkedin.com/posts/immanueljohnprofile_blockchain-web3-education-activity-6992708276928876544-ckut?utm_source=share&utm_medium=member_desktop), where engaged students delved into the realms of blockchain and its transformative potential.

**Co-Founder of KalakendraDAO:**

As a co-founder of KalakendraDAO, we aim to onboard artists to the Web3 domain and provide them with the tools and knowledge they need. Our leadership efforts include organizing and sponsoring various events:

[Metaverse Diwali - Metaverse Events](https://twitter.com/KalaKendraDAO/status/1579900492611584000?s=20)
[Kolkata Event - Sponsored by KalakendraDAO](https://twitter.com/cointimes_in/status/1564151685412700166?s=20)
[Web3 Huddle IRL Chennai](https://twitter.com/KalaKendraDAO/status/1563130276259106816?s=20)
[Web3 101 - College IRL Event](https://twitter.com/KalaKendraDAO/status/1556702919688220672?s=20)
[Blockchain 101 - College IRL Event](https://www.linkedin.com/feed/update/urn:li:activity:6992708276928876544/)
[Regional Dance Arts Onboarding IRL Event](https://twitter.com/KalaKendraDAO/status/1530072185871601664?s=20)
[OTS Community Onboard Musical Event](https://twitter.com/KalaKendraDAO/status/1486233553289760774?s=20)
[Musical Onboard IRL Event](https://twitter.com/KalaKendraDAO/status/1474821606794948609?s=20)
I also had the privilege of representing KalakendraDAO at India’s Biggest Web3 NFT Summit in Bangalore and the Web3 Conference in Goa.

These experiences have enabled me to lead and contribute to both technical and community-building efforts, aligning with my passion for education and collaboration in the evolving tech landscape.

### Mentorship experience

Yes

### Mentorship details

**Mentorship Experience:**

I have had the privilege of mentoring and guiding enthusiasts, students, and aspiring developers in various domains. My journey began with organizing and leading live workshops on Web2 technologies, introducing participants to programming concepts and fostering their interest in the tech world. I extended this mentorship to the realm of Solidity and blockchain, guiding individuals through the intricacies of smart contract development and blockchain technology.

**Mentoring in the Polkadot and Substrate Ecosystem:**

In my role as a Rust/Substrate engineer in Ternoa, a NFT-centric project in the Polkadot ecosystem, I have been actively involved in mentoring junior developers. I've shared insights into Polkadot's architecture, Substrate framework, and best practices in blockchain development. My involvement in the Substrate StackExchange platform has further allowed me to mentor and assist fellow developers facing challenges in their Substrate projects.

**Expanding Mentorship Horizons:**

Beyond my current experiences, I am keen on expanding my mentorship endeavors. I find immense satisfaction in guiding others and witnessing their growth. As a testament to this, I've already conducted live workshops covering a range of topics including Solidity, blockchain, Polkadot, and Substrate. My interest in mentorship extends to not only nurturing technical skills but also fostering a deep understanding of the underlying concepts, encouraging critical thinking, and guiding individuals towards impactful contributions in the decentralized technology landscape.

With a background in conducting workshops and hands-on sessions, I am enthusiastic about taking on more formal mentorship roles. The opportunity to share knowledge, provide guidance, and empower individuals to navigate the intricate world of blockchain and decentralized technologies is something I'm deeply passionate about.

**Comment by Immanuel-john** [comment]
@hummusonrails thank you for letting me know. looking forward for the September's review.

**Comment by zsofimajor** [comment]
Hi @Immanuel-john , thank you again for submitting your nomination to become a Hero in the Polkadot Developer Heroes program. 
We would like to inform you of an important update regarding the approval criteria for our program. After some careful consideration,  we've decided to update our criteria to minimise subjectivity as much as possible  and ensure fairness and transparency in the Hero selection process. As a result, we kindly ask that you resubmit your application following the new criteria, which you can find [here](https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md). 

Your initial application showed us your passion and dedication, and we'd love for you to build upon that. Once again, thanks a ton for your interest in the Heroes program. We're looking forward to receiving your updated application. Your support means a lot to us, and we're grateful for your understanding as we make these changes.

**Comment by zsofimajor** [comment]
Hi @Immanuel-john  this is just a gentle reminder about your hero nomination. Please note that if you don't submit an updated nomination in a week, we close this issue. You can of course open a new one any time later in the future.

**Comment by zsofimajor** [comment]
Closing this ticket now. Feel free to nominate yourself again in the future!
