### ISSUE TITLE
Add Noor into Rookie List

### ISSUE THREAD

**Issue by noormohammedb** [Polkadot-Heroes/Members#43]
### Technical expertise

I started with substrate kitties from eth Denver's shawn's workshop https://github.com/noormohammedb/substrate-workshops/tree/ethdenver
then completed substrate docs tutorials and done web3 foundation funded substrate interactive tutorial https://github.com/noormohammedb/rusty-crewmates_substrate-tutorials

### Community involvement

I am active polkadot community member in polkadot Dubai and last polkadot decoded side event i volunteered in the event to organize with the ambassador.

I am actively participating in the polkadot opengov and kusama governance  (12BpKBaSPeAVcs3PCGdPkqESdExd8oFixjTubhfJBobbEbJW, )

I have answered in substrate stackexchange and got 2 upvotes as a developer (https://substrate.stackexchange.com/questions/4174/the-wasm32-unknown-unknown-target-is-not-supported-by-default/8317#8317)

### Content creation

I didn't created any content yet, But I have plan to create a full tutorial from substrate docs to building a simple dex chain

### Leadership experience

when I was in collage I conducted couple of workshops to the student as web development and other topics

### Mentorship experience

No Mentorship experience in dotsama community 

### Mentorship details

I didn't get any mentorship from polkadot community, But I got many help when learning full stack development and web3 development, I think its because the community is very small, after being a good substrate developer defiantly i will mentor new comer into the substrate world

**Comment by hummusonrails** [comment]
Hi @noormohammedb,

You have already been accepted into the program as a Rookie. We are so delighted you are here! 🎉 

This self-nomination form is to submit yourself as a candidate for Hero status.

Please take a moment to add yourself to the Rookies list by following the instructions [here](https://github.com/Polkadot-Heroes/Members/tree/main/Rookies#contributing).
