### ISSUE TITLE
[Nomination] : JovanCBS

### ISSUE THREAD

**Issue by JovanCBS** [Polkadot-Heroes/Members#48]
### Technical expertise

https://github.com/sora-xor/sora2-network/tree/master/pallets/hermes-governance-platform

### Community involvement

No involvement.

### Content creation

No contet.

### Leadership experience

No experience.

### Mentorship experience

Yes

### Mentorship details

Ni mentorship.

**Comment by hummusonrails** [comment]
Thank you for submitting a nomination for Hero status! :sparkles:

A word about the process:

The team reviews nominations *four* times a year in March, June, September and December.
We commit to responding to every nomination within two weeks after the review process has completed.

**How does this work?** :eyes:

If you submitted this nomination in February, then it will be reviewed in March. :raised_hands:
if you submitted this nomination in November, then it will be reviewed in December. :raised_hands:

As a reminder, the criteria for review and selection for Hero status is publicly available in this [GitHub repository](https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md).

You can continue to update your nomination form with new and relevant information up until the point of review.

Have any questions? Please don't hesitate to [send us a message](mailto:heroes@parity.io)! :email:

**Comment by zsofimajor** [comment]
Hi @JovanCBS, thank you again for submitting your nomination to become a Hero in the Polkadot Developer Heroes program. 

We have briefly looked at your self-nomination, but unfortunately we haven't found enough information to make a fair evaluation. 

Please note that we have recently updated our criteria to minimise subjectivity as much as possible and ensure fairness and transparency in the Hero selection process. You can look at the new criteria [here](https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md). If you are still interested in applying to become a Hero, I'd like to encourage you to resubmit your nomination based on the updated guideline.

Thanks a ton for your interest in the Heroes program!

**Comment by zsofimajor** [comment]
Hi @JovanCBS this is just a gentle reminder about your hero nomination. Please note that if you don't submit an updated nomination in a week, we close this issue. You can of course open a new one any time later in the future.

**Comment by zsofimajor** [comment]
Closing this ticket now. Feel free to nominate yourself again in the future!
