### ISSUE TITLE
[Nomination] : 

### ISSUE THREAD

**Issue by EdinyangaOttoho** [Polkadot-Heroes/Members#53]
### Technical expertise

https://medium.com/coinmonks/creating-a-p2p-tic-tac-toe-gambling-smart-contract-on-aleph-zero-using-ink-9702f7714f55

https://medium.com/coinmonks/comparing-paritys-ink-with-solidity-evm-vs-substrate-programming-14379a79d7fc

https://medium.com/@elzucky/want-to-build-on-aleph-zero-here-are-some-prerequisites-to-get-from-the-ground-up-c3fec653415e

### Community involvement

https://substrate.stackexchange.com/questions/6187/psp22-cross-contract-call-to-get-metadata-such-as-token-decimals-and-token-name

https://substrate.stackexchange.com/questions/6913/i-have-a-problem-with-getting-the-return-type-of-balance-from-inkenvcallb

https://github.com/EdinyangaOttoho/ink-tic-tac-toe

### Content creation

https://medium.com/coinmonks/comparing-paritys-ink-with-solidity-evm-vs-substrate-programming-14379a79d7fc

https://medium.com/coinsbench/my-web3-development-journey-exploring-multiple-blockchain-networks-5cefcf328f3e

### Leadership experience

N/A

### Mentorship experience

No

### Mentorship details

N/A

**Comment by hummusonrails** [comment]
Hi @EdinyangaOttoho,

Thanks so much for your interest in the Polkadot Developer Heroes program!

Your journey as a candidate into the program starts by filling out the [sign-up form](https://info.polkadot.network/polkadot-developer-heroes). Once you do so, a member of the team will be in touch about next steps. 

All candidates once accepted join the program as Rookies, and then can self-nominate to Hero status using this form, or be recognized as a Hero by the team. The criteria for Hero status can be viewed [in this repo](https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md).

Hope to see you in the program soon!

Ben
