### ISSUE TITLE
[Nomination] : Alex Bean

### ISSUE THREAD

**Issue by AlexD10S** [Polkadot-Heroes/Members#64]
### Technical expertise

I am a Polkadot Support Engineer at Parity where I have been doing some technical work supporting Rococo:

- [Script to onboard Parachains in Rococo](https://github.com/paritytech/subport).
- [Changes in assgined_slots pallet](https://github.com/paritytech/polkadot/pull/7217)

I have created some pallets for educational purposes at some events or exploring different areas:
- [Betting pallet](https://github.com/AlexD10S/substrate-betting) for a workshop in a Hackathon
- [NFTs Royalty Pallet](https://forum.polkadot.network/t/nfts-royalty-pallet/3766)
- And collaborating in other cool projects like[ Substrate Chess]( https://github.com/SubstrateChess)

### Community involvement

- Very active  in StackExchange with more than 230 answers and  top 7 in all time reputation list: https://substrate.stackexchange.com/users/2762/alex-bean

- Active in the Polkadot online forum: https://forum.polkadot.network/u/alexd10s/summary

### Content creation

Different dive dives sessions in Youtube, explaining complex concepts:

- [XCM e2e integration testing](https://youtu.be/9CF5FAwlu2c?t=1301)
- [Weights Concepts | Polkadot Deep Dives](https://youtu.be/tIc1f5coI7U?list=PLOyWqupZ-WGsfnlpkk0KWX3uS4yg6ZztG&t=192)
- [Support Pallet | Polkadot Deep Dives](https://youtu.be/1-MKzDNlSvs?t=1875)
- [Recovery Pallet | Polkadot Deep Dives](https://www.youtube.com/watch?v=_wU5nfmYBkY)
- [Proxy Pallet | Polkadot Deep Dives](https://www.youtube.com/watch?v=zzcIAjhbAF8&list=PLOyWqupZ-WGsfnlpkk0KWX3uS4yg6ZztG&index=25)
- [Balances Pallet | Polkadot Deep Dives](https://youtu.be/_FwqB4FwWXk?list=PLOyWqupZ-WGsfnlpkk0KWX3uS4yg6ZztG&t=1441)

Participate in a Substrate Seminar Session
[Build a Betting Pallet - Substrate Seminar](https://github.com/substrate-developer-hub/substrate-seminar/blob/main/scheduled/2022/12-20-betting-pallet.md)

Some technical tutorials:
- [Add custom RPC to the node](https://hackmd.io/JpJCbu0nTa2jym0za1Tggw)
- [Parachain State Rollback](https://hackmd.io/3BAy3HEzRVO2sBFnUaBVKA)

### Leadership experience

- Judge in the [Polkadot Hackathon LATAM](https://polkadothackathonlatam.com/#jueces).

### Mentorship experience

Yes

### Mentorship details

The last year I have participate in different Hackathons as a mentor:

-  [Polkadot Metaverse](https://metaversechampionship.gg/)
-  [ETH Dublin Hackthon](https://www.ethdublin.io/).

**Comment by zsofimajor** [comment]
Hi @AlexD10S  , thank you again for submitting your nomination to become a Hero in the Polkadot Developer Heroes program. 
We would like to inform you of an important update regarding the approval criteria for our program. After some careful consideration,  we've decided to update our criteria to minimise subjectivity as much as possible  and ensure fairness and transparency in the Hero selection process. As a result, we kindly ask that you resubmit your application following the new criteria, which you can find [here](https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md). 

Your initial application showed us your passion and dedication, and we'd love for you to build upon that. Once again, thanks a ton for your interest in the Heroes program. We're looking forward to receiving your updated application. Your support means a lot to us, and we're grateful for your understanding as we make these changes.

**Comment by zsofimajor** [comment]
Hi @AlexD10S this is just a gentle reminder about your hero nomination. Please note that if you don't submit an updated nomination in a week, we close this issue. You can of course open a new one any time later in the future.

**Comment by AlexD10S** [comment]
## Scoring Framework - Alex Bean: 30 points

### Technical Expertise

| GitHub activity related to Polkadot - in the past quarter | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Is an owner or maintainer of any other open-source Polkadot ecosystem project <br>*(where the project is not the Polkadot SDK, not a Substrate based chain, not a tooling <br>or library project, or not a dapp)* |  - [Script to onboard Parachains in Rococo](https://github.com/paritytech/subport) (Automate to tool used by the ecosystem to onboard the parachain on Rococo). - [Substrate Betting](https://github.com/AlexD10S/substrate-betting)(Repository for a workshop to teach how to build a pallet) - [NFTs Royalty Pallet](https://github.com/AlexD10S/nfts-royalty)(Example of how to manage royalties of NFTs, gathering feedback from the community in the [Polkadot Forum](https://forum.polkadot.network/t/nfts-royalty-pallet/3766)) | 3 pts |

| Technical Education - in the past quarter | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Has taught a coding workshop or training session on Polkadot <br>and/or Rust in the past quarter | [How to Deploy Solidity in Polkadot at the ETH Rome](https://github.com/AlexD10S/ETH-Workshop) and [XCM e2e integration testing Deep Dive](https://youtu.be/9CF5FAwlu2c?t=1301) | 2 pts |
| Has contributed more than once to documentation for Polkadot <br>or a Polkadot ecosystem project in the past quarter | [polkadot-docs](https://github.com/substrate-developer-hub/substrate-docs/commits?author=AlexD10S) and [ink-docs](https://github.com/paritytech/ink-docs/commits?author=AlexD10S) | 2 pts |
| Has published a technical research paper or article <br>about Rust or Polkadot with more than 60% of own content | [Add custom RPC to the node](https://hackmd.io/JpJCbu0nTa2jym0za1Tggw) and [Parachain State Rollback](https://hackmd.io/3BAy3HEzRVO2sBFnUaBVKA)  | 2 pts |
| Is in the top 10% on StackExchange | [My StackExchange profile](https://substrate.stackexchange.com/users/2762/alex-bean) | 1 pts |
| Has been graduated from the Polkadot Blockchain Academy | No | 0 |

### Community involvement

| Activity on the Polkadot Forum - in the past quarter | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Has authored more than one topic on the forum in the past quarter | [Forum profile link](https://forum.polkadot.network/u/alexd10s/summary) | 1 pts |
| Has added more than one comment to topics on the forum in the past quarter | [Forum profile link](https://forum.polkadot.network/u/alexd10s/summary) | 1 pts |

| Polkadot forum technical contribution - Tech talk category | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Created a technical topic for discussion in the tech talk section of the forum in the past quarter <br> *(Non tech topics can still be submitted in this category, but will not count here.)*|  [Link to post](https://forum.polkadot.network/t/frontend-development-experience/4393) | 1 pts |
| Gave technical responses to 3 or more topics in the tech talk section of the forum in the past quarter | [Forum profile link](https://forum.polkadot.network/u/alexd10s/summary) | 1  pts |

| Attendance at Polkadot-related events - in the past quarter | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Has attended two or more Polkadot-related events in the past quarter <br>*(e.g. meetups, other community events that's not sub0, Decoded or a hackathon)* | [Polkadot Brunch at ETH Rome](https://lu.ma/p3v87fab) | 1 pts |
| Has attended most recent sub0 | The previous one in person, the last one online [Event link(s)](https://www.polkadot.network/ecosystem/events/sub0/ ) | 1 pts |
| Has attended most recent Decoded | The previous one online, the last one in person [Event link(s)](https://www.polkadot.network/ecosystem/events/decoded-2023/) | 1 pts |

| Participation at a Polkadot hackathon (Polkadot-focused or has a Polkadot track) | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Has participated at a hackathon with a submitted project in the past quarter | Not as a player  | 0 |
| Won a hackathon with a submitted project in the past quarter | No | 0 |

| Mentoring within the Heroes program | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Has been mentoring folk(s) within the Heroes program | No | 0 |

| Polkadot Ambassador Program | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Is a Polkadot Ambassador/Senior Ambassador/Head Ambassador | No | 0 |

| Community moderation | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Moderator or active contributor in Polkadot-focused online communities <br>*(e.g., Telegram, Discord)* | No | 0 |

### Content creation

| Written content - in the past quarter | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Has produced more than one technical blog post in a Polkadot specific topic | [Add custom RPC to the node](https://hackmd.io/JpJCbu0nTa2jym0za1Tggw) and [Parachain State Rollback](https://hackmd.io/3BAy3HEzRVO2sBFnUaBVKA)  | 2 pts |
| Has produced any interactive educational content related to Polkadot <br> *(e.g. coding challenges, quizzes)*| No  | 0 |
| Has produced any Polkadot-related educational content in other languages than English | [Translate ink-docs to Spanish](https://github.com/paritytech/ink-docs/commits?author=AlexD10S) | 2 pts |
| Has created and shared Polkadot-related infographics or visual content in the past quarter | No | 0 |

| Recorded content - in the past quarter | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Produced more than one technical-focused video on own Youtube (or other platform) or podcast channel in the past quarter | Deep Dives Learning Sessions on Twitch (And Youtube): [XCM e2e integration testing](https://youtu.be/9CF5FAwlu2c?t=1301), [Weights Concepts](https://youtu.be/tIc1f5coI7U?list=PLOyWqupZ-WGsfnlpkk0KWX3uS4yg6ZztG&t=192), [Support Pallet](https://youtu.be/1-MKzDNlSvs?t=1875), [Recovery Pallet](https://www.youtube.com/watch?v=_wU5nfmYBkY), [Proxy Pallet](https://www.youtube.com/watch?v=zzcIAjhbAF8&list=PLOyWqupZ-WGsfnlpkk0KWX3uS4yg6ZztG&index=25), [Balances Pallet](https://youtu.be/_FwqB4FwWXk?list=PLOyWqupZ-WGsfnlpkk0KWX3uS4yg6ZztG&t=1441) | 2 pts |
| Has been a guest speaker on a Polkadot-focused YouTube (or other platform) channel or podcast in the past quarter | [Build a Betting Pallet - Substrate Seminar](https://github.com/substrate-developer-hub/substrate-seminar/blob/main/scheduled/2022/12-20-betting-pallet.md) | 1 pts |

 Public speaking - in the past quarter | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Served as a speaker or panelist at conferences or events on <br>a Polkadot-related topic in the past quarter |  [Polkadot Brunch at ETH Rome: Introduction to Polkadot](https://lu.ma/p3v87fab)|  1 pts |

### Leadership experience

| Organization of or participation at Polkadot-related tech focused events - in the past quarter | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Has organized or hosted a Polkadot related technical community meetup in the past quarter |  [Help to organize and present an introduction to Polkadot at Polkadot Brunch at ETH Rome](https://twitter.com/i/status/1710583995983855992)   | 2 pts |
| Has organized or hosted a Polkadot related technical workshop in the past quarter | [Help to organise and run a workshop on How to Deploy Solidity in Polkadot at the ETH Rome](https://x.com/filippoweb3/status/1710362235111915864?s=20)  | 2 pts |
| Has organized other community initiatives (eg. Polkadot-focused hackathon or <br>coding challenge) in the past quarter | No | 0 |
| Served as a judge or mentor at Polkadot hackathons in the past quarter | Judge in [Polkadot Hackathon LATAM](https://polkadothackathonlatam.com/#jueces), Mentor in [ETH Dublin]([ETH Dublin Hackthon](https://www.ethdublin.io/) and  [Polkadot Metaverse](https://metaversechampionship.gg/) | 1pts |


| Active involvement in Polkadot based projects | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Founded or is leading a Polkadot-related working group or special interest group | No | 0 |
| Is holding an engineering leadership position in a Polkadot-based project | No | 0 |


| Leading discussions in the online space | Scoring via | Points to earn|
| :----------- | :----------- | :----------- |
| Is creating and managing a Polkadot-focused media outlet or publication <br>*(Including discussion starters, with twitter threads, acive discussions started in chat rooms, forums, or productions similar to DotLeap, AAG, any newsletters etc.)* | No | 0 |

**Comment by zsofimajor** [comment]
@AlexD10S Thanks for submitting your nomination! Great job! 

Aaaaand... drumroll please! 
🚀 Congratulations on becoming the first Hero in the Polkadot Developer Heroes program! The org team is going to reach out to you with more details!
