### ISSUE TITLE
[Nomination] : Tomas Rawski

### ISSUE THREAD

**Issue by rtomas** [Polkadot-Heroes/Members#70]
### Technical expertise

+ [Open Payroll](https://github.com/ankas-lab/openPayroll) | ink! + use-ink
+ [Open Dream Colors](https://opencolors.tomasrawski.com.ar/) | ink! + use-ink
+ [Subgraph for Lens Protocol](https://github.com/rtomas/lens-protocol-subgraph) | Assemblyscript
+ Small fix: https://github.com/paritytech/contracts-ui/pull/491
+ Small fix: https://github.com/paritytech/contracts-ui/pull/490

### Community involvement

+ Decoded 2022 in Buenos Aires
+ Polkadot Blockchain Academy in Buenos Aires

### Content creation

+ [Polkadot Learning Path](https://github.com/rtomas/polkadot-learning-path)
+ [Tutorial: how to use Open Dream Colors and ask for tokens ](https://rtomas.hashnode.dev/how-to-use-the-open-dream-colors-art-app-with-your-own-wallet-and-ask-for-rocs)
+ [Tutorial: how to create a smart contract in ink!](https://rtomas.hashnode.dev/create-a-smart-contract-in-ink)
+ [Tutorial in spanish to use the education&art web Dream Colors](https://rtomas.hashnode.dev/como-usar-la-obra-open-dream-colors-el-color-de-tus-suenos-con-tu-propia-billetera-virtual-y-pedir-por-los-tokens-rocs)
+ [Tutorial: Analize, compile and deploy a smart contract](https://rtomas.hashnode.dev/analyze-compile-and-deploy-a-smart-contract-on-a-polkadot-parachain)
+ [Polkadot Blockchain Academy Experience](https://rtomas.hashnode.dev/polkadot-blockchain-academy-experience)

### Leadership experience

none

### Mentorship experience

No

### Mentorship details

-

**Comment by zsofimajor** [comment]
Hi @rtomas , thank you again for submitting your nomination to become a Hero in the Polkadot Developer Heroes program. 
We would like to inform you of an important update regarding the approval criteria for our program. After some careful consideration,  we've decided to update our criteria to minimise subjectivity as much as possible  and ensure fairness and transparency in the Hero selection process. As a result, we kindly ask that you resubmit your application following the new criteria, which you can find [here](https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md). 

Your initial application showed us your passion and dedication, and we'd love for you to build upon that. Once again, thanks a ton for your interest in the Heroes program. We're looking forward to receiving your updated application. Your support means a lot to us, and we're grateful for your understanding as we make these changes.
