### ISSUE TITLE
[Nomination] : Meharab

### ISSUE THREAD

**Issue by Meharab** [Polkadot-Heroes/Members#74]
### Technical expertise

I am new here, I do not have any skill.

### Community involvement

I am new here, I do not have any involvement.

### Content creation

I am new here, I do not have any content.

### Leadership experience

I am new here, I do not have any leadership experience.

### Mentorship experience

No

### Mentorship details

I am new here, I do not have any mentorship experience.

**Comment by hummusonrails** [comment]
Hey there,

I noticed that you wrote you have no experience here yet, which is fine, but then I'd recommend applying to the program generally and coming in as a Rookie! All program participants come in as Rookies, and then once they feel like they have met the criteria for Hero status, they can self-nominate as a Hero.

You can apply to the program here: https://www.polkadot.network/development/developer-heroes/

The criteria for Hero status is on this repository at this link: https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md

I'm going to close this nomination as you have not demonstrated any of the criteria for Hero status, but we are so excited to see you apply to the program and start your journey! 🚀
