### ISSUE TITLE
[Nomination] : Denis Pisarev

### ISSUE THREAD

**Issue by TriplEight** [Polkadot-Heroes/Members#78]
### Technical expertise

Most of the Parity and Substrate dev repositories. IBP program. Contributions to the related open-source tooling.

### Community involvement

I participate in most of the Polkadot-related and other blockchain events and conferences, I connect people and projects, mentor and help various teams. By far gave two talks on CI and efficient Rust compilation. A technical advisor in 6 ecosystem projects. I mostly read forums, Polkadot StackExchange and proposals, sometimes comment and vote.

### Content creation

https://www.youtube.com/watch?v=FAwEgQNcZ00
https://www.youtube.com/watch?v=PxFs3jzbWOc

### Leadership experience

I founded and led 2 teams at Parity, found and led to hiring of more than 10 employees at Parity and W3f.

### Mentorship experience

Yes

### Mentorship details

I won the first mentor prize on the last ETHberlin conference. I've been a Product Expert and have quite some achievements in Google's PE program.

**Comment by zsofimajor** [comment]
Hi @TriplEight , thank you again for submitting your nomination to become a Hero in the Polkadot Developer Heroes program. 
We would like to inform you of an important update regarding the approval criteria for our program. After some careful consideration,  we've decided to update our criteria to minimise subjectivity as much as possible  and ensure fairness and transparency in the Hero selection process. As a result, we kindly ask that you resubmit your application following the new criteria, which you can find [here](https://github.com/Polkadot-Heroes/Members/blob/main/Heroes_Review_Criteria.md). 

Your initial application showed us your passion and dedication, and we'd love for you to build upon that. Once again, thanks a ton for your interest in the Heroes program. We're looking forward to receiving your updated application. Your support means a lot to us, and we're grateful for your understanding as we make these changes.

**Comment by zsofimajor** [comment]
Hi @TriplEight this is just a gentle reminder about your hero nomination. Please note that if you don't submit an updated nomination in a week, we close this issue. You can of course open a new one any time later in the future.

**Comment by zsofimajor** [comment]
Closing this ticket now. Feel free to nominate yourself again in the future!
