### ISSUE TITLE
[Nomination] : 

### ISSUE THREAD

**Issue by sourabupadhya123** [Polkadot-Heroes/Members#85]
### Attendance at Polkadot-related events

https://www.crowdcast.io/e/substrate-seminar
https://www.crowdcast.io/e/metaverse1
https://www.crowdcast.io/e/j7v16d3j
https://www.crowdcast.io/e/introducing-web3name

### Attendance at sub0

2021

https://youtu.be/hSoSA6laK3Q?si=jjAPGfxxBXJ_Kmvg

### Attendance at Polkadot Decoded

2023

https://www.youtube.com/watch?v=GIB1WeVuJD0&list=PLOyWqupZ-WGtxijJor37g5GmUqVgUvGDt&index=3

### Participation at a Polkadot hackathon (Polkadot-focused or has a Polkadot track)

**Polkadot Hello World Hackathon**

1. https://www.polkadot.network/blog/hello-world-by-polkadot-take-the-challenge/

- https://github.com/sourabupadhya123/Launch-A-Local-Substrate-Development-Chain
- https://github.com/sourabupadhya123/Build-And-Run-A-Local-Phala-Network
- https://github.com/sourabupadhya123/Hello-World-Polkadot
- https://github.com/sourabupadhya123/Polkadot-Challenge-Moonbeam
- https://github.com/sourabupadhya123/Using-Remix-And-MetaMask-On-Moonbeam

### Participation at a Polkadot hackathon (Polkadot-focused or has a Polkadot track)

**Polkadot Hello World Hackathon**

1. https://www.polkadot.network/blog/hello-world-by-polkadot-take-the-challenge/

- https://github.com/sourabupadhya123/Launch-A-Local-Substrate-Development-Chain
- https://github.com/sourabupadhya123/Build-And-Run-A-Local-Phala-Network
- https://github.com/sourabupadhya123/Hello-World-Polkadot
- https://github.com/sourabupadhya123/Polkadot-Challenge-Moonbeam
- https://github.com/sourabupadhya123/Using-Remix-And-MetaMask-On-Moonbeam

### Polkadot Ambassador Program

No, I'm not a Polkadot Ambassador

### Technical blog posts

- https://sourabeth.medium.com/mine-avalanche-network-learning-pathway-experience-eae6127639de
- https://sourabeth.medium.com/mine-celo-network-learning-experience-dba05c9b2071
- https://sourabeth.medium.com/mine-learning-experience-with-secret-network-41806902f4c4
- https://sourabeth.medium.com/mine-learning-experience-with-near-protocol-development-f8262d01898e

**Comment by zsofimajor** [comment]
Hi @sourabupadhya123 
Thank you for your nomination! We reviewed your submission, and unfortunately I have to inform you that you haven't collected enough points to become a Hero just now. 

However, your submission shows that you are on the right path! Keep on collecting the XP!

This issue will now be closed, but you can submit a new nomination any time in the future.

**Comment by sourabupadhya123** [comment]
Thank You
