### ISSUE TITLE
[Nomination] : Deepak Chaudhary

### ISSUE THREAD

**Issue by Aideepakchaudhary** [Polkadot-Heroes/Members#93]
### Code contribution to a Substrate-based chain project

https://github.com/Aideepakchaudhary/proof-of-stake-node-template
https://github.com/Aideepakchaudhary/Substrate-node-template-with-babe-and-frontier

### Owned or maintained project(s)

https://github.com/Aideepakchaudhary/proof-of-stake-node-template
https://github.com/Aideepakchaudhary/Substrate-node-template-with-babe-and-frontier
https://github.com/IBC-Media/Crowdfunding-template
https://github.com/IBC-Media/Voter-interface-template
https://github.com/IBC-Media/Action-tracker-template

### Coding workshops or training sessions

https://www.youtube.com/watch?v=IcA4ydG2SWQ&list=PLpq17qyFqg3KRLi_BNzccN2tXfHzQ3f2y&index=11
https://www.youtube.com/watch?v=GlPTUot4v5c&list=PLpq17qyFqg3KRLi_BNzccN2tXfHzQ3f2y&index=12
https://www.youtube.com/watch?v=CbZusKUh87s&list=PLpq17qyFqg3ITZSlRAty3YprkZ-G1p42x&index=13

### Contribution to documentation

https://github.com/w3f/polkadot-wiki/pull/4673
https://github.com/w3f/polkadot-wiki/pull/4669

### R&D

https://medium.com/@aideepakchaudhary/divorcing-the-relay-and-parachain-node-in-the-collator-c30aba093221

### StackExchange profile

https://substrate.stackexchange.com/users/555/deepak-chaudhary

### Attendance at Polkadot-related events

[polkadot blockchain india](https://www.polkadotnowindia.com/)

### Polkadot Ambassador Program

None

### Community moderation

Discord: aideepak

### Technical blog posts

https://medium.com/@aideepakchaudhary/divorcing-the-relay-and-parachain-node-in-the-collator-c30aba093221

### Interactive educational content

https://www.youtube.com/watch?v=IcA4ydG2SWQ&list=PLpq17qyFqg3KRLi_BNzccN2tXfHzQ3f2y&index=11
https://www.youtube.com/watch?v=GlPTUot4v5c&list=PLpq17qyFqg3KRLi_BNzccN2tXfHzQ3f2y&index=12
https://www.youtube.com/watch?v=CbZusKUh87s&list=PLpq17qyFqg3ITZSlRAty3YprkZ-G1p42x&index=13

### Recorded own content

https://www.youtube.com/watch?v=IcA4ydG2SWQ&list=PLpq17qyFqg3KRLi_BNzccN2tXfHzQ3f2y&index=11
https://www.youtube.com/watch?v=GlPTUot4v5c&list=PLpq17qyFqg3KRLi_BNzccN2tXfHzQ3f2y&index=12
https://www.youtube.com/watch?v=CbZusKUh87s&list=PLpq17qyFqg3ITZSlRAty3YprkZ-G1p42x&index=13

### Recorded content as a guest

https://www.youtube.com/watch?v=IcA4ydG2SWQ&list=PLpq17qyFqg3KRLi_BNzccN2tXfHzQ3f2y&index=11
https://www.youtube.com/watch?v=GlPTUot4v5c&list=PLpq17qyFqg3KRLi_BNzccN2tXfHzQ3f2y&index=12
https://www.youtube.com/watch?v=CbZusKUh87s&list=PLpq17qyFqg3ITZSlRAty3YprkZ-G1p42x&index=13

### Public speaking

https://www.linkedin.com/feed/update/urn:li:activity:7080082734185951234/

**Comment by zsofimajor** [comment]
H @Aideepakchaudhary ,

Thank you for your nomination! We reviewed your submission, and unfortunately I have to inform you that you haven't collected enough points to become a Hero at this point.

However, your submission shows that you are on the right path to gather more experience! 
FYI, we are working on coming up with some suggestions for [rankings](https://github.com/orgs/Polkadot-Heroes/discussions/2#discussioncomment-7640153), your application will definitely fall into one of the future ranks! 

This issue will now be closed, but you can submit a new nomination any time in the future.
